<?php

use App\Contracts\System\AssetHelperInterface;
use App\Infrastructure\Config\Config;

/**
 * Page: Manual Code Input (Search)
 *
 * Formular zur manuellen Verifizierung eines SmartCodes.
 *
 * Suchmaske für die manuelle Genehmigungsprüfung.
 * Bietet Kontrolleuren ein Eingabefeld zur Eingabe von System-Codes oder Kennzeichen.
 *
 * @var array $settings
 * @var AssetHelperInterface $asset
 * @var Config $config
 * @var string $appRoot
 * @var string $cspNonce
 * @var string|null $error Optionale Fehlermeldung, wenn ein eingegebener Code nicht existiert.
 */
$layout = 'public';
$pageTitle = 'Genehmigung prüfen';
?>

<div class="c-tab-content-container o-container o-container--small u-padding-y-xl">
    <div class="c-card c-card--primary u-margin-auto">
        <header class="c-card__header u-text-center">
            <h2 class="u-margin-none">
                <img src="<?php echo $asset->url('assets/img/icons/action-search.webp'); ?>"
                     class="c-icon c-icon--md"
                     alt=""> Manuelle Prüfung
            </h2>
            <p class="u-text-muted u-margin-top-s">Geben Sie den vollständigen SmartCode ein.</p>
        </header>
        <div class="c-card__body">

            <?php require $appRoot . '/templates/partials/frontend/alerts.phtml'; ?>

            <form action="check"
                  method="GET"
                  class="c-form">
                <div class="c-form-group u-margin-bottom-l">
                    <input type="text"
                           name="code"
                           aria-label="Gutscheincode eingeben"
                           class="c-form-input c-form-input--code u-text-center"
                           placeholder="z.B. 6Y5C"
                           required
                           autofocus
                           autocomplete="off">
                </div>
                <button type="submit"
                        class="c-button--primary c-button--submit u-width-100">Code jetzt prüfen</button>
            </form>
        </div>
    </div>
</div>
