<?php
/**
 * @var int   $adminLevel
 * @var array $stats
 */
?>
<div class="c-stats-grid u-margin-bottom-l">
    <?php if ($adminLevel < 3) { ?>
        <div class="c-card stats-box">
            <small>Einnahmen (Zeitraum)</small>
            <div class="u-font-xl u-font-bold"><?php echo \number_format($stats['total_revenue'] ?? 0, 2, ',', '.'); ?> €</div>
        </div>
    <?php } ?>

    <div class="c-card stats-box">
        <small>Anträge / PKW / LKW</small>
        <div class="u-font-l">
            <?php echo $stats['total_count'] ?? 0; ?>
            (<?php echo $stats['types']['pkw'] ?? 0; ?> / <?php echo $stats['types']['lkw'] ?? 0; ?>)
        </div>
    </div>
</div>
