<?php
/**
 * @var array<string, array<\App\Core\Entity\Permit>> $groups
 */
?>
<section class="c-card">
    <table class="c-table">
        <thead>
            <tr>
                <th>Kennung / Name</th>
                <th>Abgelaufen am</th>
                <th class="u-text-right">Aktion</th>
            </tr>
        </thead>
        <tbody>
            <?php if (empty($groups['expired'])) { ?>
                <tr>
                    <td colspan="3" class="u-text-center u-text-muted u-padding-y-m">
                        Keine abgelaufenen Genehmigungen in diesem Zeitraum.
                    </td>
                </tr>
            <?php } else { ?>
                <?php foreach ($groups['expired'] as $permit) { ?>
                    <tr class="u-opacity-50">
                        <td>
                            <code><?php echo \htmlspecialchars($permit->code); ?></code><br>
                            <small><?php echo \htmlspecialchars($permit->owner->name); ?></small>
                        </td>
                        <td><?php echo $permit->validity->bis->format('d.m.Y'); ?></td>
                        <td class="u-text-right">
                            <a href="check.php?code=<?php echo $permit->code; ?>" target="_blank" class="c-button c-button--secondary c-button--small">👁</a>
                        </td>
                    </tr>
                <?php } ?>
            <?php } ?>
        </tbody>
    </table>
</section>
