<?php

// SPDX-License-Identifier: LicenseRef-Proprietary
// Copyright (c) 2026 Felix Maywald alias RaptorXilef. All rights reserved.
// Usage without explicit permission is strictly prohibited.
// See LICENSE.md for full license details.

// Path: templates/components/_favicon.phtml

/**
 * Component: Favicon
 *
 * Globale einbindung der Favicons.
 */
?>

<link rel="icon"
      type="image/png"
      href="/assets/img/fav/favicon-96x96.png?v=20260524"
      sizes="96x96" />
<link rel="icon"
      type="image/svg+xml"
      href="/assets/img/fav/favicon.svg?v=20260524" />
<link rel="shortcut icon"
      href="/assets/img/fav/favicon.ico?v=20260524" />
<link rel="apple-touch-icon"
      sizes="180x180"
      href="/assets/img/fav/apple-touch-icon.png?v=20260524" />
<meta name="apple-mobile-web-app-title"
      content="KGA Zufahrts-Manager" />
<link rel="manifest"
      href="/assets/img/fav/site.webmanifest?v=20260524" />
