<?php

/**
 * Component: Favicon
 *
 * Globale einbindung der Favicons.
 *
 * Path: templates/components/_favicon.phtml
 *
 * SPDX-License-Identifier: LicenseRef-Proprietary
 */
?>

<link rel="icon"
      type="image/png"
      href="/assets/img/fav/favicon-96x96.png?v=20260524"
      sizes="96x96" />
<link rel="icon"
      type="image/svg+xml"
      href="/assets/img/fav/favicon.svg?v=20260524" />
<link rel="shortcut icon"
      href="/assets/img/fav/favicon.ico?v=20260524" />
<link rel="apple-touch-icon"
      sizes="180x180"
      href="/assets/img/fav/apple-touch-icon.png?v=20260524" />
<meta name="apple-mobile-web-app-title"
      content="KGA Einfahrts-Manager" />
<link rel="manifest"
      href="/assets/img/fav/site.webmanifest?v=20260524" />
