name: Build Production Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Wichtig für Upload
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Behebt die Node-Warnung
      VERSION: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.3
          # https://github.com/marketplace/actions/checkout

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies (No Dev)
        run: composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist

      - name: Create Release ZIPs
        run: |
          # 1. INSTALL-PAKET (Für Neuinstallationen)
          # Hier packen wir die originalen Dateien (ohne .default) ein.
          zip -r kga-zufahrts-manager-install-${{ env.VERSION }}.zip config/ public/ src/ templates/ vendor/ CHANGELOG.md README.md composer.json package.json -x "src/assets/*"

          # 2. BASH-MAGIC: Umbenennen der Config-Dateien für das Update
          for file in config/*.php; do
            filename=$(basename "$file")
            # Wir ignorieren jetzt sql_schema.php UND permissions.php
            if [ "$filename" != "sql_schema.php" ] && [ "$filename" != "permissions.php" ]; then
              mv "$file" "config/${filename%.php}.default.php"
            fi
          done

          # 3. UPDATE-PAKET (Für Bestandskunden)
          # Hier sind die config-Dateien nun als .default.php benannt und werden so ins ZIP gepackt.
          zip -r kga-zufahrts-manager-update-${{ env.VERSION }}.zip config/ public/ src/ templates/ vendor/ CHANGELOG.md README.md composer.json package.json -x "src/assets/*" "public/assets/img/user_images/*" "public/assets/img/group_images/*"

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v3.0.0
          # https://github.com/marketplace/actions/gh-release
        with:
          files: |
            kga-zufahrts-manager-update-${{ env.VERSION }}.zip
            kga-zufahrts-manager-install-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
