name: Build Production Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3' # anpassen

    - name: Install dependencies (No Dev)
      run: composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist

    - name: Create Release ZIP
      run: |
        # Wir packen exakt nur die Whitelist-Ordner/Dateien ins ZIP
        # Und schließen darin gezielt die Entwicklungs- & Nutzer-Assets aus
        zip -r kga-update.zip public/ src/ templates/ vendor/ CHANGELOG.md README.md composer.json package.json -x "src/assets/*" "public/assets/img/user_images/*" "public/assets/img/group_images/*"

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: kga-update.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
