name: Build Production Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Wichtig für Upload
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Behebt die Node-Warnung
      VERSION: ${{ github.ref_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.3
          # https://github.com/marketplace/actions/checkout

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies (No Dev)
        run: composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist

      - name: Create Release ZIPs
        run: |
          # ZIP 1: Update-Paket (mit Ausschlüssen)
          # Wir packen exakt nur die Whitelist-Ordner/Dateien ins ZIP
          # Und schließen darin gezielt die Entwicklungs- & Nutzer-Assets aus
          zip -r kga-zufahrts-manager-update-${{ env.VERSION }}.zip config/ public/ src/ templates/ vendor/ CHANGELOG.md README.md composer.json package.json -x "src/assets/*" "public/assets/img/user_images/*" "public/assets/img/group_images/*"

          # ZIP 2: Install-Paket (mit anderen Ausschlüssen)
          zip -r kga-zufahrts-manager-install-${{ env.VERSION }}.zip config/ public/ src/ templates/ vendor/ CHANGELOG.md README.md composer.json package.json -x "src/assets/*"

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v3.0.0
          # https://github.com/marketplace/actions/gh-release
        with:
          files: |
            kga-zufahrts-manager-update-${{ env.VERSION }}.zip
            kga-zufahrts-manager-install-${{ env.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
